Install_intro_xml
php/doc-it pull request #10
Opened 2021-04-12 21:07 UTC by lucalzetta

Provo a inserire un solo file.

2021-04-20 07:38 UTC, DavidePastore commented
Ciao @lucalzetta. Mi sapresti indicare un file che hai aggiornato tenendo conto dei miei ultimi commenti? In questo modo potrei procedere con la revisione.

2021-04-20 09:43 UTC, lucalzetta commented
Ciao @DavidePastore , in questa pull INSTALL_INTRO_XML, il file intro.xml l'ho tradotto cercando di tener cont dei tuoi commenti.
Però in ogni pull request che vedo su php-it, vedo tutta la storia delle mie traduzioni. Ancora non ho capito come fare per evidenziare un solo file in una pull request. Ho dovuto rallentare un po' perché questo lavoro mi sta assorbendo troppo tempo. Comunque non sono fermo, sto lavorando ad un file pittosto lungo nella directory install. Ciao

2021-04-23 16:45 UTC, DavidePastore commented
Ciao @lucalzetta. Appena possibile faccio una revisione del file che hai indicato. Nel frattempo, ti consiglio di dare una lettura a https://git-scm.com/book/it/v2/Git-Branching-Branches-in-a-Nutshell e fare un po' di esperimenti su una repository totalmente vuota di tua proprietà, in modo da avere la possibilità di fare tutte le prove che vuoi, riuscendo a comprendere più facilmente i meccanismi che stanno dietro a git.

2021-04-27 08:42 UTC, DavidePastore requested changes
Ciao @lucalzetta. Ho aggiunto dei commenti sul file `install/intro.xml`. Puoi focalizzarti sul sistemare i problemi che ti ho indicato prima di continuare a tradurre altri file, in modo da procedere passo passo? Grazie mille!

2021-04-27 08:42 UTC, DavidePastore commented on install/intro.xml
> +    fatte al server.
Questa sezione ha un rigo in meno rispetto alla versione inglese. Andrebbe sistemato.

2021-04-27 08:42 UTC, DavidePastore commented on install/intro.xml
> +    </link>. PHP-GTK non è incluso nelle distribuzioni ufficiali di PHP.
Questa sezione ha un rigo in meno rispetto alla versione inglese. Andrebbe sistemato.

2021-04-27 08:42 UTC, DavidePastore commented on install/intro.xml
> +    per riga di comando alle seguenti sezioni.
Questa sezione ha un rigo in meno rispetto alla versione inglese. Andrebbe sistemato.

2021-04-27 08:42 UTC, DavidePastore commented on install/intro.xml
> +    essere trovate a <link xlink:href="&url.php.downloads;">&url.php.downloads;</link>.
Questa sezione ha un rigo in meno rispetto alla versione inglese. Andrebbe sistemato.

2021-04-27 08:42 UTC, DavidePastore commented on install/intro.xml
> +-->
Rigo vuoto finale mancante.

2021-04-27 08:42 UTC, DavidePastore commented on install/intro.xml
> +    section:
Io farei:
```xml
    come descritto nella
    sezione
    <link linkend="intro-whatcando">cosa può fare PHP?</link>:
```

2021-04-29 08:26 UTC, DavidePastore commented on install/intro.xml
> +    per riga di comando alle seguenti sezioni.
Questo problema è ancora presente.

2021-04-29 08:26 UTC, DavidePastore commented on install/intro.xml
> +    essere trovate a <link xlink:href="&url.php.downloads;">&url.php.downloads;</link>.
Questo problema è ancora presente.

2021-04-29 08:27 UTC, DavidePastore commented on install/intro.xml
> +    section:
Credo che il modo indicato da me sia migliore, dato che rispetta le stesse righe del file originale e allo stesso tempo non contiene "section".

2021-04-29 08:41 UTC, DavidePastore commented on install/intro.xml
> +    affittato e vedere i risultati sul vostro browser.
Ho notato che in questo file ci sono delle organizzazioni che vanno a spostare il contenuto rispetto a quello originale del file inglese, usando delle righe differenti. Questo ovviamente non è un problema in alcune situazioni al limite, ma nella maggior parte dei casi ha senso rispettare lo stesso ordine della versione inglese, in modo da semplificare quanto più possibile la manutenzione del file in futuro. Prendo come esempio questa sezione. Nella versione inglese è scritta così:

```xml
   <para>
    For the first and most common form, you need three things:
    PHP itself, a web server and a web browser. You
    probably already have a web browser, and depending on
    your operating system setup, you may also have a web
    server (e.g. Apache on Linux and macOS; IIS on Windows).
    You may also rent webspace at a company. This way, you
    don't need to set up anything on your own, only write
    your PHP scripts, upload it to the server you rent, and
    see the results in your browser. 
   </para>
```

nella tua invece abbiamo:

```xml
   <para>
    Per la prima e più comune forma, sono necessarie tre cose: 
    PHP, un server web e un browser web, probabilmente avrete già un 
    web browser, e, conformemente alle impostazioni del vostro 
    sistema operativo, potreste avere anche un server web (es. 
    Apache su Linux e macOS o IIS su Windows). Potete anche aver 
    noleggiato dello spazio web da un fornitore. In questo modo 
    non avrete bisogno di impostare niente da parte vostra, solo 
    scrivere i vostri script PHP, caricarli sul server che avete 
    affittato e vedere i risultati sul vostro browser. 
   </para>
```

Come la scriverei io, in modo da renderla più facile da modificare in futuro:

```xml
   <para>
    Per la prima e più comune forma, sono necessarie tre cose: 
    PHP, un server web e un browser web.
    Probabilmente avrete già un web browser, e, conformemente alle
    impostazioni del vostro sistema operativo, potreste avere anche un server
    web (es. Apache su Linux e macOS o IIS su Windows).
    Potete anche aver noleggiato dello spazio web da un fornitore. In questo modo 
    non avrete bisogno di impostare niente da parte vostra, solo scrivere
    i vostri script PHP, caricarli sul server che avete affittato e
    vedere i risultati sul vostro browser. 
   </para>
```

Quando ti parlavo di situazioni al limite, facevo riferimento al caso delle parole "web server" scritte su due righe differenti nella versione inglese ("web" su una e "server" sulla successiva). Nella traduzione, dovendo usare "server web", invertiamo l'ordine, portando "server" su una riga e "web" sulla sucessiva.

2021-04-29 08:42 UTC, DavidePastore commented
@lucalzetta , ho aggiunto un ulteriore commento. Quel tipo di modifica andrebbe fatta su tutto il file in questione. Fammi sapere se hai dubbi su qualcosa.

2021-04-29 10:05 UTC, lucalzetta commented
install/intro.xml l'ho modificato considerando i tuoi commenti. Ho anche
aggiunto un commento di chiarimento sulla richiesta. Dovresti vederlo. Ciao

Il mar 20 apr 2021, 09:38 Davide Pastore ***@***.***> ha
scritto:

> Ciao @lucalzetta <https://github.com/lucalzetta>. Mi sapresti indicare un
> file che hai aggiornato tenendo conto dei miei ultimi commenti? In questo
> modo potrei procedere con la revisione.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/php/doc-it/pull/10#issuecomment-823051335>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APE3ZWDVEWZID7YVSS6KC3LTJUVOXANCNFSM422BPTLQ>
> .
>

2021-04-29 10:11 UTC, DavidePastore commented
@lucalzetta, Se hai aggiunto un commento, purtroppo non lo riesco a vedere. Puoi anche dare un'occhiata al commento che ho inserito prima? Eccolo qui: https://github.com/php/doc-it/pull/10#discussion_r622848241

2021-04-29 10:31 UTC, lucalzetta commented
Ok, mi sto perdendo perché vedo i commenti dal telefono e fatico a visualizzare le righe complete del file. C'è un modo per mettere uno di fianco all'altra la versione su cui stai lavorando e quella in Inglese o salti sempre da una pagina all'altra?

2021-04-29 10:50 UTC, DavidePastore commented
@lucalzetta, in genere utilizzo Notepad++ per avere i due file aperti in contemporanea e con lo scorrimento verticale sincronizzato. Ti basta cliccare sul tab di uno dei due file con il tasto destro e scegliere "Sposta nell'altra vista" e successivamente vai sulla voce di menu "Visualizza" e "Sincronizza scorrimento verticale".

2021-07-04 10:48 UTC, DavidePastore commented
Ciao @lucalzetta . Come stai? È da un po' che non ci si sente. Volevo capire se hai bisogno di supporto per quanto riguarda le modifiche che ti ho richiesto o se è tutto chiaro. Grazie mille e buona giornata.

2021-07-04 20:31 UTC, lucalzetta commented
Ciao Davide, ho ricevuto le tue mail, mi sembra di aver capito che c'è
un'applicazione disponibile per facilitare il lavoro di traduzione. Tenterò
di installarla al più presto per completare l'opera. Mi ero fermato perché
avendo già eseguito la traduzione abbastanza sgrezzata di quasi metà dei
documenti e non trovando riscontro ho preferito aspettare prima di
applicarmi ulteriormente rischiando di approfondire eventuali errori già
commessi.
Cercherò di installare il programma, spero di farcela e di revisionare i
documenti elaborati per perfezionare la chiusura della traduzione. Mi farò
vivo nei prossimi giorni (vacanze permettendo :)).

Il giorno dom 4 lug 2021 alle ore 12:48 Davide Pastore <
***@***.***> ha scritto:

> Ciao @lucalzetta <https://github.com/lucalzetta> . Come stai? È da un po'
> che non ci si sente. Volevo capire se hai bisogno di supporto per quanto
> riguarda le modifiche che ti ho richiesto o se è tutto chiaro. Grazie mille
> e buona giornata.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/php/doc-it/pull/10#issuecomment-873564206>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APE3ZWAJGKDWBNANDWQPC2LTWA4BTANCNFSM422BPTLQ>
> .
>

2021-07-05 08:17 UTC, DavidePastore commented
@lucalzetta, va benissimo! Se hai bisogno di supporto, chiedi senza problemi. 😄

2023-09-02 13:25 UTC, closed without merging